[package]
name = "goodbooks-recommender"
version = "0.1.0"
authors = ["Ben Marx <ben@bgmarx.com>"]

[dependencies]
csv = "1.0.0"
failure = "0.1.1"
rand = "0.5.4"
reqwest = "0.8.6"
sbr = "0.4.0"
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"
